### ISSUE TITLE
Add/Override sysctls and environment variables via user-data

### ISSUE THREAD

**Issue by axelfontaine** [vmify/vmify#6]
In order to be able to reuse the same AMI across for example multiple environments with different configurations, it should be possible to add/override sysctls and environment variables via user-data.

User-data format proposal:
```yaml
sysctl:
  KEY1: "value 1"
  KEY2: "value 2"
env:
  KEY1: "value 1"
  KEY2: "value 2"
```
